# Generated by Django 4.2.3 on 2023-07-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.URLField(default='https://picsum.photos/seed/picsum/200/300', max_length=250),
            preserve_default=False,
        ),
    ]
