# Generated by Django 4.2.3 on 2023-08-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_resume',
            field=models.TextField(null=True),
        ),
    ]
