# Generated by Django 4.2.3 on 2023-08-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_actor_actor_image_actor_actor_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='actor_image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='actor_resume',
            field=models.TextField(null=True),
        ),
    ]
