# Generated by Django 4.2.3 on 2023-09-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_awards_movie_awards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='awards',
            field=models.ManyToManyField(blank=True, to='cinema.awards'),
        ),
    ]
