# Generated by Django 4.2.3 on 2023-09-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_movie_awards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Awards',
            new_name='Award',
        ),
    ]
